### ISSUE TITLE
doesnt seem to be searching

### ISSUE THREAD

**Issue by lessthantom** [nosmokingbandit/watcher#124]
Hey 

seems a bit odd but i dont think my watcher install is actually searching, ive added a couple films which are definately available made sure they are within the size parameters ive set, dont include any of the ignored words. and they dont appear 

also when i manually hit search, it tries to search for maybe a second then just goes back to the nothing found screen.

ill try debug when i get chance but any help would be great 

im on mac OS Sierra python 2.7.10

UPDATE 

so ive reinstalled a fresh copy reinstalled python and generally been fiddling, and whats odd is that i opened it, then i noticed my hard drive is writing and watcher has sent 3 movies to nzbget but they still show as wanted and if you press search it immediately stops searching and nothing is found...

**Comment by lessthantom** [comment]
i seem to have an error on the PREDB search and the SSLv3 handshake



URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
INFO 2017-01-08 08:43:09,617 core.sqldb.get_movie_details: Retreving details for tt5740806.
INFO 2017-01-08 08:43:09,619 core.rss.predb.check_one: Checking predb.me for new available releases for Coin Heist.
ERROR 2017-01-08 08:43:09,670 core.rss.predb.search_rss: PREDB search.
Traceback (most recent call last):
  File "/Applications/watcher/core/rss/predb.py", line 79, in search_rss
    results_xml = urllib2.urlopen(request).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
INFO 2017-01-08 08:43:09,671 core.sqldb.get_movie_details: Retreving details for tt5740806.
INFO 2017-01-08 08:43:09,685 core.sqldb.get_search_results: Retreving Search Results for tt5740806.
INFO 2017-01-08 08:43:09,693 core.sqldb.get_user_movies: Retreving list of user's movies.

**Comment by lessthantom** [comment]
update again 

so i looked through some closed issues and saw something about https

the error i have looks to be from ssl PREDB.me so i edited the predb.py and changed it to http rather than https and its working again for search
