### ISSUE TITLE
Recent update broke the Web UI 

### ISSUE THREAD

**Issue by Crowley007** [nosmokingbandit/watcher#140]
Traceback (most recent call last):
  File "c:\Git\watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "c:\Git\watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\Git\watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\Git\watcher\templates\status.py", line 39, in default
    self.movie_list()
  File "c:\Git\watcher\templates\status.py", line 81, in movie_list
    score = int(data['tomatorating'][0])
ValueError: invalid literal for int() with base 10: 'N'`

**Comment by nosmokingbandit** [comment]
Fixed in https://github.com/nosmokingbandit/watcher/commit/4c29993d14c68b1f96836a79a51b6f9bd9ee92f7.
