### ISSUE TITLE
Database tables not updated

### ISSUE THREAD

**Issue by ywLBhGk2noZLbY7** [nosmokingbandit/watcher#169]
#### What happened?
Updated Watcher, now getting the following error in my browser:

```
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/templates/status.py", line 48, in default
    self.movie_list()
  File "/opt/watcher/app/templates/status.py", line 90, in movie_list
    if data['score'] == 'N/A':
KeyError: 'score'
```
#### What was supposed to happen?
[update_tables](https://github.com/nosmokingbandit/watcher/blob/1710dd32d3979a705d38b96132184881a752ef0f/core/sqldb.py#L476) should run and update the tables, so 'score' exists.
#### Logs
stdout:
```
/opt/watcher/app/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
[17/Jan/2017:15:08:04] ENGINE Listening for SIGHUP.
[17/Jan/2017:15:08:04] ENGINE Listening for SIGTERM.
[17/Jan/2017:15:08:04] ENGINE Listening for SIGUSR1.
[17/Jan/2017:15:08:04] ENGINE Bus STARTING
[17/Jan/2017:15:08:04] ENGINE Started monitor thread '_TimeoutMonitor'.
[17/Jan/2017:15:08:04] ENGINE Serving on http://0.0.0.0:9090
[17/Jan/2017:15:08:04] ENGINE Bus STARTED
[17/Jan/2017:15:08:30] HTTP
Request Headers:
  ${stripped}
[17/Jan/2017:15:08:30] HTTP
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/templates/status.py", line 48, in default
    self.movie_list()
  File "/opt/watcher/app/templates/status.py", line 90, in movie_list
    if data['score'] == 'N/A':
KeyError: 'score'
Config file found, merging any new options.
172.19.0.5 - - [17/Jan/2017:15:08:30] "GET /status/ HTTP/1.1" 500 1433 "" "${stripped}"
172.19.0.5 - - [17/Jan/2017:15:08:30] "GET /favicon.ico HTTP/1.1" 200 5430 "${stripped}" "${stripped}"
```

Log file:
```
INFO 2017-01-17 15:08:03,795 __main__.<module>: SQL DB not found. Creating.
INFO 2017-01-17 15:08:03,797 core.sqldb.create_database: Creating tables.
INFO 2017-01-17 15:08:03,824 core.version.update_check: Checking git for a new version.
INFO 2017-01-17 15:08:04,498 core.version.update_check: Current local hash: d6ce82499493108413954e51fcb55185c044678f
INFO 2017-01-17 15:08:04,507 core.version.update_check: Update found:
INFO 2017-01-17 15:08:04,507 core.version.update_check: {'status': u'behind', 'new_hash': '2b6ee4c995739f868566523424be5ca551be43fd', 'behind_count': 30, 'local_hash': 'd6ce82499493108413954e51fcb55185c044678f'}
INFO 2017-01-17 15:08:04,507 core.notification.add: Creating notification:
INFO 2017-01-17 15:08:04,507 core.notification.add: {'body': u'Click <a href="update_now"><u>here</u></a> to update now.<br/> Click <a href="https://github.com/nosmokingbandit/watcher/compare/2b6ee4c995739f868566523424be5ca551be43fd...d6ce82499493108413954e51fcb55185c044678f"><u>here</u></a> to view changes.', 'title': u'30 Updates Available', 'params': {'extendedTimeOut': 0, 'tapToDismiss': 0, 'timeOut': 0}, 'type': 'update'}
INFO 2017-01-17 15:08:04,546 cherrypy.error.error: [17/Jan/2017:15:08:04] ENGINE Listening for SIGHUP.
INFO 2017-01-17 15:08:04,546 cherrypy.error.error: [17/Jan/2017:15:08:04] ENGINE Listening for SIGTERM.
INFO 2017-01-17 15:08:04,546 cherrypy.error.error: [17/Jan/2017:15:08:04] ENGINE Listening for SIGUSR1.
INFO 2017-01-17 15:08:04,546 cherrypy.error.error: [17/Jan/2017:15:08:04] ENGINE Bus STARTING
INFO 2017-01-17 15:08:04,548 cherrypy.error.error: [17/Jan/2017:15:08:04] ENGINE Started monitor thread '_TimeoutMonitor'.
INFO 2017-01-17 15:08:04,667 cherrypy.error.error: [17/Jan/2017:15:08:04] ENGINE Serving on http://0.0.0.0:9090
INFO 2017-01-17 15:08:04,668 cherrypy.error.error: [17/Jan/2017:15:08:04] ENGINE Bus STARTED
INFO 2017-01-17 15:08:30,141 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-01-17 15:08:30,146 cherrypy.error.139660780941712.error: [17/Jan/2017:15:08:30] HTTP
Request Headers:
  ${stripped}
ERROR 2017-01-17 15:08:30,147 cherrypy.error.139660780941712.error: [17/Jan/2017:15:08:30] HTTP
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/templates/status.py", line 48, in default
    self.movie_list()
  File "/opt/watcher/app/templates/status.py", line 90, in movie_list
    if data['score'] == 'N/A':
KeyError: 'score'
```

I can provide the database if required, however, for obvious reasons I'd prefer not to.

**Comment by nosmokingbandit** [comment]
Can you email it to me at watchernzb@gmail.com

I'm the only person who will look at it.

I've tested the database migration many times and I haven't been able to reproduce and problems so I don't really know where to start.

You should also have a backup database named watcher.sqlite.DATE in watcher/db/. Send that to me as well if you don't mind so I can attempt to migrate it on my own install.

**Comment by ywLBhGk2noZLbY7** [comment]
Found the issue, so I won't email you:

https://github.com/nosmokingbandit/watcher/blob/master/watcher.py#L87

`if not os.path.isfile('watcher.sqlite'):`

Should be

`if not os.path.isfile(core.DB_FILE):`

**Comment by nosmokingbandit** [comment]
Your pull request was merged, so I'm going to close this.
