### ISSUE TITLE
nzbget post processing still broken  dc24117

### ISSUE THREAD

**Issue by bleomycin** [nosmokingbandit/watcher#174]
Running  dc24117 with latest nzbget post process script, nzbget 17.1. Post processing still seems to be broken. Mono 4.6.2, debian jessie.

Server log:

```
INFO 2017-01-17 18:04:48,054 core.postprocessing.POST: #################################
INFO 2017-01-17 18:04:48,054 core.postprocessing.POST: Post-processing request received.
INFO 2017-01-17 18:04:48,054 core.postprocessing.POST: #################################
INFO 2017-01-17 18:04:48,054 core.postprocessing.get_filename: Finding movie file name.
INFO 2017-01-17 18:04:48,055 core.postprocessing.get_filename: Post-processing file /media/raid/incoming/watcher/removed 2013.720p BluRay x264-YIFY.Watcher/removed.2013.720p.BluRay.x264.YIFY.mp4.
INFO 2017-01-17 18:04:48,055 core.postprocessing.POST: Parsing release name for information.
INFO 2017-01-17 18:04:48,055 core.postprocessing.POST: Gathering release information.
INFO 2017-01-17 18:04:48,055 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-01-17 18:04:48,055 core.sqldb.get_single_search_result: Retreving search result details for https://api.nzb.su/getnzb/removed.
INFO 2017-01-17 18:04:48,056 core.postprocessing.get_movie_info: Searchresult found by guid.
INFO 2017-01-17 18:04:48,056 core.postprocessing.get_movie_info: Searching local database by imdbid.
INFO 2017-01-17 18:04:48,056 core.sqldb.get_movie_details: Retreving details for ttsomething.
INFO 2017-01-17 18:04:48,057 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
INFO 2017-01-17 18:04:48,057 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-01-17 18:04:48,057 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-01-17 18:04:48,057 core.updatestatus.searchresults: Marking guid https://api.nzb.su/getnzb/removed as Finished.
INFO 2017-01-17 18:04:48,058 core.updatestatus.searchresults: Marking https://api.nzb.su/getnzb/removed as Finished in SEARCHRESULTS.
INFO 2017-01-17 18:04:48,058 core.sqldb.update: Updating https://api.nzb.su/getnzb/removed to Finished in SEARCHRESULTS.
INFO 2017-01-17 18:04:48,059 core.updatestatus.searchresults: Successfully marked https://api.nzb.su/getnzb/removed as Finished in SEARCHRESULTS.
INFO 2017-01-17 18:04:48,060 core.updatestatus.markedresults: Marking https://api.nzb.su/getnzb/removed as Finished in MARKEDRESULTS.
INFO 2017-01-17 18:04:48,060 core.sqldb.update: Updating https://api.nzb.su/getnzb/removed to Finished in MARKEDRESULTS.
INFO 2017-01-17 18:04:48,066 core.updatestatus.markedresults: Successfully marked https://api.nzb.su/getnzb/removed as Finished in MARKEDRESULTS.
INFO 2017-01-17 18:04:48,066 core.postprocessing.complete: Setting MOVIE status.
INFO 2017-01-17 18:04:48,066 core.sqldb.get_distinct: Getting distinct values for ttsomething in SEARCHRESULTS
INFO 2017-01-17 18:04:48,067 core.updatestatus.movie_status: Setting MOVIES ttsomething status to Finished.
INFO 2017-01-17 18:04:48,067 core.sqldb.update: Updating ttsomething to Finished in MOVIES.
INFO 2017-01-17 18:04:48,068 core.sqldb.update: Updating ttsomething to 2017-01-17 in MOVIES.
INFO 2017-01-17 18:04:48,069 core.sqldb.update: Updating ttsomething to 605 in MOVIES.
ERROR 2017-01-17 18:04:48,076 cherrypy.error.139679315101776.error: [17/Jan/2017:18:04:48] HTTP 
Traceback (most recent call last):
  File "/opt/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/core/postprocessing.py", line 93, in POST
    response = json.dumps(self.complete(data), indent=2, sort_keys=True)
  File "/opt/watcher/core/postprocessing.py", line 547, in complete
    response = self.renamer(data)
  File "/opt/watcher/core/postprocessing.py", line 646, in renamer
    new_name = self.compile_path(renamer_string, data).replace(':', core.CONFIG['Postprocessing']['replaceillegal'])
  File "/opt/watcher/core/postprocessing.py", line 609, in compile_path
    new_string = string.format(**data)
ValueError: unmatched '{' in format
INFO 2017-01-17 18:04:48,076 cherrypy.error.139679315101776.error: [17/Jan/2017:18:04:48] HTTP 
Request Headers:
  HOST: 192.168.2.9:9090
  CONNECTION: close
  Remote-Addr: 192.168.2.7
  Content-Length: 302
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  ACCEPT-ENCODING: identity
```

nzbget log:

```
Tue Jan 17 18:09:45 2017        INFO    watcher: Sending something.2016.720p.WEB-DL.Watcher to Watcher as Complete.
Tue Jan 17 18:09:45 2017        INFO    watcher: Traceback (most recent call last):
Tue Jan 17 18:09:45 2017        INFO    watcher:   File "/home/nzbget/nzbget/scripts/watcher.py", line 61, in <module>
Tue Jan 17 18:09:45 2017        INFO    watcher:     response = json.loads(urllib2.urlopen(request, timeout=600).read())
Tue Jan 17 18:09:45 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
Tue Jan 17 18:09:45 2017        INFO    watcher:     return opener.open(url, data, timeout)
Tue Jan 17 18:09:45 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 437, in open
Tue Jan 17 18:09:45 2017        INFO    watcher:     response = meth(req, response)
Tue Jan 17 18:09:45 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
Tue Jan 17 18:09:45 2017        INFO    watcher:     'http', request, response, code, msg, hdrs)
Tue Jan 17 18:09:45 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 475, in error
Tue Jan 17 18:09:45 2017        INFO    watcher:     return self._call_chain(*args)
Tue Jan 17 18:09:45 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
Tue Jan 17 18:09:45 2017        INFO    watcher:     result = func(*args)
Tue Jan 17 18:09:45 2017        INFO    watcher:   File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
Tue Jan 17 18:09:45 2017        INFO    watcher:     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
Tue Jan 17 18:09:45 2017        INFO    watcher: urllib2.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by nosmokingbandit** [comment]
What are the renaming/mover strings you have in Settings>Post Processing?

**Comment by bleomycin** [comment]
Crap, just caught my typo thanks to your reply. Sorry for wasting your time! I had:

Enable Renamer: {title.{year}

**Comment by nosmokingbandit** [comment]
That won't matter after 7881fd192cf95cf66ba92e94d1b8d6783d51f02a anyway.

Python's str.format() is awesome, but chokes if there is an extra brace or a {tag} it isn't aware of.

Now you can go nuts and put whatever braces you want in your renamer. You get a brace. And you get a brace!
