### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by t4nkw4rt** [nosmokingbandit/watcher#189]
#### What happened?
tried to add a movie from imdb by name. Watcher refused to add the movie, asked for imdb-id instead.
I've entered the id and watcher hangs. On restart, I get a "500 Internal Server Error".

#### What was supposed to happen?
Well, no 500 error  :)

#### How can I reproduce this?
I'd say, add the same movie again :)

error msg in browser after restart:
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/home/t4nkw4rt/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/home/t4nkw4rt/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/t4nkw4rt/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/home/t4nkw4rt/watcher/templates/status.py", line 48, in default
    self.movie_list()
  File "/home/t4nkw4rt/watcher/templates/status.py", line 105, in movie_list
    span(data['rated'], cls='rated')
  File "/home/t4nkw4rt/watcher/templates/dominate/tags.py", line 63, in __init__
    super(html_tag, self).__init__(*args, **kwargs)
  File "/home/t4nkw4rt/watcher/templates/dominate/dom_tag.py", line 93, in __init__
    self.add(*args)
  File "/home/t4nkw4rt/watcher/templates/dominate/dom_tag.py", line 204, in add
    raise ValueError('%r not a tag or string.' % obj)
ValueError: None not a tag or string.

email on the way

**Comment by nosmokingbandit** [comment]
Email me with the imdbid

watchernzb@gmail.com.

Include a link to this issue so I know who you are.

**Comment by t4nkw4rt** [comment]
after deleting old watcher doing a fresh install, I still had to enter this movie by imdb-id. No error 500 so far :)
