### ISSUE TITLE
'module' object has no attribute 'plugins' (watcher fails to start)

### ISSUE THREAD

**Issue by ShoGinn** [nosmokingbandit/watcher#197]
#### What happened?
After update it fails to start
#### What was supposed to happen?
it is supposed to start.
#### How can I reproduce this?
try and start watcher 

```
-- Unit watcher.service has begun starting up.
Jan 28 21:23:18 mediaserver python2.7[838]: Config file found, merging any new options.
Jan 28 21:23:18 mediaserver python2.7[838]: Database found.
Jan 28 21:23:18 mediaserver python2.7[838]: Traceback (most recent call last):
Jan 28 21:23:18 mediaserver python2.7[838]:   File "/opt/watcher/watcher.py", line 105, in <module>
Jan 28 21:23:18 mediaserver python2.7[838]:     root = cherrypy.tree.mount(App(),
Jan 28 21:23:18 mediaserver python2.7[838]:   File "/opt/watcher/core/app.py", line 20, in __init__
Jan 28 21:23:18 mediaserver python2.7[838]:     self.ajax = ajax.Ajax()
Jan 28 21:23:18 mediaserver python2.7[838]:   File "/opt/watcher/core/ajax.py", line 34, in __init__
Jan 28 21:23:18 mediaserver python2.7[838]:     self.plugins = plugins.Plugins()
Jan 28 21:23:18 mediaserver python2.7[838]: AttributeError: 'module' object has no attribute 'Plugins'
Jan 28 21:23:18 mediaserver systemd[1]: watcher.service: Control process exited, code=exited status=1
Jan 28 21:23:18 mediaserver systemd[1]: Failed to start Watcher Daemon.
-- Subject: Unit watcher.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit watcher.service has failed.
-- 
-- The result is failed.
Jan 28 21:23:18 mediaserver systemd[1]: watcher.service: Unit entered failed state.
Jan 28 21:23:18 mediaserver systemd[1]: watcher.service: Failed with result 'exit-code'.

```
this is for the commit

```
commit 42c1bc5902776656abec9f59a072fe8c76923db3
Merge: 73e2ed0 3ada19c
Author: nosmokingbandit <nosmokingbandit@gmail.com>
Date:   Sat Jan 28 22:22:41 2017 -0500

    Fix ignoring hidden 'dotfiles'

```

**Comment by ShoGinn** [comment]
So I decided to troubleshoot this myself (python newb)

did a:

`find . -name "*.pyc" -exec rm -rf {} \;`

and a 

`find . -name "*.sqlite" -exec rm -rf {}\;`

but keeping my config..

Now it starts..

I think it is a valid issue; how do we prevent this error?

**Comment by nosmokingbandit** [comment]
This is apparently git being stupid. I renamed a directory and git apparently doesn't remove the old one.

My server updated fine, but one of my testing copies didn't. Removal of the watcher/core/plugins directory fixes it.

I don't understand why Git won't remove a directory when I tell it to...
