### ISSUE TITLE
SAB Post-Process script on Windows

### ISSUE THREAD

**Issue by mattenz** [nosmokingbandit/watcher#198]
Really happy that there's something new to replace Couchpotato!

I'm working on setting up Watcher on Windows (Server 2016) and while it's all running fine, I'm having issues with the Post Processing script for Sab.  This is the error:
`Sending <file>.Watcher to Watcher as Complete.`
`Traceback (most recent call last):`
  `File "C:\Program Files (x86)\SABnzbd\scripts\sabnzbd.py", line 69, in <module>`
    `response = json.loads(urllib2.urlopen(request, timeout=600).read())`
  `File "C:\Python27\lib\urllib2.py", line 154, in urlopen`
    `return opener.open(url, data, timeout)`
  `File "C:\Python27\lib\urllib2.py", line 437, in open`
    `response = meth(req, response)`
`  File "C:\Python27\lib\urllib2.py", line 550, in http_response`
    `'http', request, response, code, msg, hdrs)`
  `File "C:\Python27\lib\urllib2.py", line 475, in error`
    `return self._call_chain(*args)`
  `File "C:\Python27\lib\urllib2.py", line 409, in _call_chain`
    `result = func(*args)`
  `File "C:\Python27\lib\urllib2.py", line 558, in http_error_default`
   ` raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)`
`urllib2.HTTPError: HTTP Error 500: Internal Server Error`

I did edit the script file to have the following:
`    'watcherapi': '<myapi>', ` 
`    'watcheraddress': 'http://server.domain.local:8087/',  `
`    'sabkey': '<mysabapi>',  `
`    'sabhost': 'server.domain.local',  `
`    'sabport': '8085'  `
`

**Comment by soundjester** [comment]
I am getting a similar error in SAB (end result being the same error 500).

The Watcher logs report that it is receiving a post-processing request, but it seems to error out on a lack of OMDB

```
INFO 2017-01-29 18:31:26,686 core.postprocessing.POST: #################################
INFO 2017-01-29 18:31:26,686 core.postprocessing.POST: Post-processing request received.
INFO 2017-01-29 18:31:26,686 core.postprocessing.POST: #################################
INFO 2017-01-29 18:31:26,686 core.postprocessing.get_filename: Finding movie file.
INFO 2017-01-29 18:31:26,699 core.postprocessing.get_filename: Post-processing file /mnt/Movies/Folder/Movie.mkv.
INFO 2017-01-29 18:31:26,700 core.postprocessing.POST: Parsing release name for information.
INFO 2017-01-29 18:31:26,705 core.postprocessing.parse_filename: Parsing filename doesn't look accurate. Parsing parent folder name.
INFO 2017-01-29 18:31:26,705 core.postprocessing.parse_filename: Found {'title': u'MovieTitle'} in parent folder.
INFO 2017-01-29 18:31:26,705 core.postprocessing.POST: Gathering release information.
INFO 2017-01-29 18:31:26,705 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-01-29 18:31:26,705 core.sqldb.get_single_search_result: Retreving search result details for http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY.
INFO 2017-01-29 18:31:26,708 core.postprocessing.get_movie_info: Searchresult found by guid.
INFO 2017-01-29 18:31:26,708 core.postprocessing.get_movie_info: Searching local database by imdbid.
INFO 2017-01-29 18:31:26,708 core.sqldb.get_movie_details: Retreving details for tt0072431.
INFO 2017-01-29 18:31:26,709 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
ERROR 2017-01-29 18:31:26,709 cherrypy.error.34494137616.error: [29/Jan/2017:18:31:26] HTTP 
Traceback (most recent call last):
  File "/usr/share/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/watcher/core/postprocessing.py", line 77, in POST
    data.update(self.get_movie_info(data))
  File "/usr/share/watcher/core/postprocessing.py", line 389, in get_movie_info
    data['rated'] = self.omdb.get_info(title, year, imdbid=data['imdbid'], tags=['Rated'])[0]
AttributeError: 'Postprocessing' object has no attribute 'omdb'
INFO 2017-01-29 18:31:26,710 cherrypy.error.34494137616.error: [29/Jan/2017:18:31:26] HTTP 
Request Headers:
  HOST: 192.168.1.71:9090
  CONNECTION: close
  Remote-Addr: 192.168.1.73
  Content-Length: 330
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
```

**Comment by nosmokingbandit** [comment]
Should be ok after b9a4b46d4a232560e6995b8932083338302fbfeb.

**Comment by soundjester** [comment]
Hmm,  Everything "appears" to be working on the post-processing side (e.g. folder gets create, files renamed/moved, etc).  However, it seems like the error has walked it's way up the script somehow.

```
INFO 2017-01-30 15:17:49,375 core.postprocessing.POST: #################################
INFO 2017-01-30 15:17:49,375 core.postprocessing.POST: Post-processing request received.
INFO 2017-01-30 15:17:49,375 core.postprocessing.POST: #################################
INFO 2017-01-30 15:17:49,375 core.postprocessing.get_filename: Finding movie file.
INFO 2017-01-30 15:17:49,384 core.postprocessing.get_filename: Post-processing file /mnt/Movies/ZZPostProc/Folder/Movie.mkv.
INFO 2017-01-30 15:17:49,384 core.postprocessing.POST: Parsing release name for information.
INFO 2017-01-30 15:17:49,386 core.postprocessing.parse_filename: Found {'group': u'NoGroup.Watcher.mkv', 'title': u'Movie Title', 'resolution': u'1080p', 'codec': u'x264', 'year': 1974, 'container': u'mkv', 'audio': u'DTS', 'quality': u'BluRay'} in filname.
INFO 2017-01-30 15:17:49,386 core.postprocessing.POST: Gathering release information.
INFO 2017-01-30 15:17:49,386 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-01-30 15:17:49,386 core.sqldb.get_single_search_result: Retreving search result details for http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=e239be244799e84bcf22a04309994c89a1e2f44a.
INFO 2017-01-30 15:17:49,387 core.postprocessing.get_movie_info: Guid not found.
INFO 2017-01-30 15:17:49,387 core.postprocessing.get_movie_info: Searching local database for downloadid.
INFO 2017-01-30 15:17:49,387 core.sqldb.get_single_search_result: Retreving search result details for SABnzbd_nzo_ZPiLrL.
INFO 2017-01-30 15:17:49,388 core.postprocessing.get_movie_info: Unable to find local data for release. Searching OMDB.
INFO 2017-01-30 15:17:49,388 core.postprocessing.get_movie_info: Searching omdb for Young Frankenstein 1974
INFO 2017-01-30 15:17:49,448 core.postprocessing.get_movie_info: Data found on OMDB.
INFO 2017-01-30 15:17:49,448 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-01-30 15:17:49,449 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-01-30 15:17:49,449 core.updatestatus.searchresults: Marking guid http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=e239be244799e84bcf22a04309994c89a1e2f44a as Finished.
INFO 2017-01-30 15:17:49,449 core.updatestatus.searchresults: Guid http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=e239be244799e84bcf22a04309994c89a1e2f44a not found in SEARCHRESULTS.
INFO 2017-01-30 15:17:49,450 core.updatestatus.markedresults: Marking http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=e239be244799e84bcf22a04309994c89a1e2f44a as Finished in MARKEDRESULTS.
INFO 2017-01-30 15:17:49,450 core.sqldb.update: Updating http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=e239be244799e84bcf22a04309994c89a1e2f44a to Finished in MARKEDRESULTS.
INFO 2017-01-30 15:17:49,452 core.updatestatus.markedresults: Successfully marked http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=e239be244799e84bcf22a04309994c89a1e2f44a as Finished in MARKEDRESULTS.
INFO 2017-01-30 15:17:49,452 core.postprocessing.complete: Setting MOVIE status.
INFO 2017-01-30 15:17:49,452 core.sqldb.get_distinct: Getting distinct values for tt0072431 in SEARCHRESULTS
INFO 2017-01-30 15:17:49,453 core.updatestatus.movie_status: Setting MOVIES tt0072431 status to Wanted.
INFO 2017-01-30 15:17:49,453 core.sqldb.update: Updating tt0072431 to Wanted in MOVIES.
INFO 2017-01-30 15:17:49,454 core.sqldb.update: Updating tt0072431 to 2017-01-30 in MOVIES.
INFO 2017-01-30 15:17:49,455 core.sqldb.update: Updating tt0072431 to None in MOVIES.
INFO 2017-01-30 15:17:49,456 core.postprocessing.renamer: Renaming Movier.mkv to Movie TItle (1974) - BluRay - 1080p.mkv
INFO 2017-01-30 15:17:49,468 core.postprocessing.mover: Moving /mnt/Movies/ZZPostProc/MovieFolder/Movie (1974) - BluRay - 1080p.mkv to /mnt/Movies/Young Frankenstein (1974)
INFO 2017-01-30 15:17:49,475 core.postprocessing.mover: Copying and renaming any extra files.
ERROR 2017-01-30 15:17:49,486 cherrypy.error.34494162768.error: [30/Jan/2017:15:17:49] HTTP 
Traceback (most recent call last):
  File "/usr/share/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/watcher/core/postprocessing.py", line 97, in POST
    title = response['title']
KeyError: 'title'
INFO 2017-01-30 15:17:49,486 cherrypy.error.34494162768.error: [30/Jan/2017:15:17:49] HTTP 
Request Headers:
  HOST: 192.168.1.71:9090
  CONNECTION: close
  Remote-Addr: 192.168.1.73
  Content-Length: 330
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  ACCEPT-ENCODING: identity
```

**Comment by mattenz** [comment]
Yeah that's basically what I'm seeing in the logs in Watcher as well although I have few more lines of errors

`ERROR 2017-01-31 11:48:18,012 cherrypy.error.51631776.error: [31/Jan/2017:11:48:18] HTTP `
`Traceback (most recent call last):`
  `File "c:\watcher\lib\cherrypy\_cprequest.py", line 670, in respond`
  `  response.body = self.handler()`
`  File "c:\watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__`
`    self.body = self.oldhandler(*args, **kwargs)`
 ` File "c:\watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__`
    ` return self.callable(*self.args, **self.kwargs)`
`  File "c:\watcher\core\postprocessing.py", line 78, in POST`
`    data.update(self.get_movie_info(data))`
`  File "c:\watcher\core\postprocessing.py", line 390, in get_movie_info`
`    data['rated'] = self.omdb.get_info(title, year, imdbid=data['imdbid'], tags=['Rated'])[0]`
`UnboundLocalError: local variable 'title' referenced before assignment`
`INFO 2017-01-31 11:48:18,167 cherrypy.error.51631776.error: [31/Jan/2017:11:48:18] HTTP `

**Comment by soundjester** [comment]
So it 'seems' like the response json is one level up from where it wants to be [when set on line 95](https://github.com/nosmokingbandit/watcher/blob/master/core/postprocessing.py#L95).

The response JSON I get at that spot is as follows:

```
{'status': u'finished', 
'tasks': {'update_movie_status': 'true', 
	  'mover': {'enabled': 'true', 'response': u'true'}, 
	  'renamer': {'enabled': 'true', 'response': u'true'}, 
 	  'cleanup': {'enabled': 'true', 'response': u'true'}, 
	  u'http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=21ffbda2278338f427c9dc6aa0d36d6bf680af9f': {'update_MARKEDRESULTS': u'true', 'update_SEARCHRESULTS': u'true'}
	}, 
'data': {u'status': u'Finished', 
	 u'predb': u'found', 
	 'videocodec': '', 
	 u'poster': u'images/poster/tt2543164.jpg', 
	 u'added_date': u'2017-01-16', 
	 'orig_filename': u'/mnt/Movies/Folder/Movie - web-dl - 1080p.mkv', 
	 'new_file_location': u'/mnt/Movies/Folder (2016)/Movie (2016) - web-dl - 1080p.mkv', 
	 'releasegroup': '', 
	 u'rated': u'PG-13', 
	 'year': u'2016', 
	 'path': u'/mnt/Movies/Folder/Movie', 
	 'guid': u'http://192.168.1.71:5075/getnzb?apikey=MYAPIKEY&searchresultid=21ffbda2278338f427c9dc6aa0d36d6bf680af9f', 
	 'audiocodec': '', 
	 u'finished_date': '2017-01-31', 
	 'apikey': u'WATCHERAPIKEY', 
	 'container': u'mkv', 
	 'downloadid': u'SABnzbd_nzo_3aML6m', 
	 'title': u'Arrival', 
	 u'url': u'https://www.themoviedb.org/movie/329865', 
	 'imdbid': u'tt2543164', 
	 u'release_date': u'2016-11-10', 
	 'filename': u'/mnt/Movies/ZZPostProc/Folder/Title - web-dl - 1080p.mkv', 
	 'source': u'web-dl', 
	 u'score': u'6.4', 
	 'mode': u'complete', 
	 u'finished_score': 705, 
	 'resolution': u'1080p'}
}
```

It seems that the script wants items from within the `data` key, but it can't quite get there the way the JSON is returned.  If would seem that rather than `response = self.complete(data)` it should be `response = self.complete(data)['data']`, which looks a little strange, but...  This works in my limited test scenario (SAB -> Watcher), but I am not sure that NZBGet returns the same JSON.

Also, it seems the postprocessing script now returns `Finished` instead of `finished` and being case sensitive, the SAB script interprets this response as an error status.

**Comment by nosmokingbandit** [comment]
So I've made a LOT of changes to the back-end stuff since I last looked at this. Are you still having trouble?

**Comment by soundjester** [comment]
It's actually been a while since anything downloaded for me so I lost track if this. I'll force something through and see what happens.

I noticed that you updated the code that affected this a while ago, so I am hopeful...

**Comment by mattenz** [comment]
Over the last week it's been working well for me.
