### ISSUE TITLE
IMDB RSS script fails with out-of-date config

### ISSUE THREAD

**Issue by Technifocal** [nosmokingbandit/watcher#199]
f647553cf90d1c5f39cb9fd885a0e469554994aa broke the IMDB script, as the IMDB script still refers to `quality['Filters'] = core.CONFIG['Filters']` [here](https://github.com/nosmokingbandit/watcher/blob/master/core/rss/imdb.py#L141), which no longer exists, resulting in:

```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "./watcher/core/cp_plugins/taskscheduler.py", line 114, in task
    self.func()
  File "./watcher/core/scheduler.py", line 181, in sync_rss
    imdb_rss.get_rss(rss_url)
  File "./watcher/core/rss/imdb.py", line 51, in get_rss
    self.sync_new_movies(movies)
  File "./watcher/core/rss/imdb.py", line 141, in sync_new_movies
    quality['Filters'] = core.CONFIG['Filters']
KeyError: 'Filters'
```

**Comment by nosmokingbandit** [comment]
Fixed in commit 8c6a84f20d3ac2dd4c5eba9ca312b76b7a078ab4
