### ISSUE TITLE
Movie status info popup not appearing.

### ISSUE THREAD

**Issue by soundjester** [nosmokingbandit/watcher#204]
Small bug encountered with [8b39d94](https://github.com/nosmokingbandit/watcher/commit/8b39d94935d13dbb41692344d4565cce62cecca8)
#### What happened?
The `sort` variable on line ~247 of core/sqldb.py never gets set if `prefersmaller` is not in the config.cfg file.

This throws the following error when pulling up the found NZB list (movie_status_popup.py):

```
ERROR 2017-02-02 19:39:40,081 cherrypy.error.34475652688.error: [02/Feb/2017:19:39:40] HTTP 
Traceback (most recent call last):
  File "/usr/share/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/share/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/share/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/watcher/core/ajax.py", line 76, in movie_status_popup
    return msp.html(imdbid)
  File "/usr/share/watcher/templates/movie_status_popup.py", line 40, in html
    self.result_list(imdbid, quality)
  File "/usr/share/watcher/templates/movie_status_popup.py", line 68, in result_list
    results = self.sql.get_search_results(imdbid, quality)
  File "/usr/share/watcher/core/sqldb.py", line 254, in get_search_results
    command = u'SELECT * FROM {} WHERE imdbid="{}" ORDER BY score DESC, size {}'.format(TABLE, imdbid, sort)
UnboundLocalError: local variable 'sort' referenced before assignment
```

See PR #203

**Comment by nosmokingbandit** [comment]
This is fixed as of https://github.com/nosmokingbandit/watcher/commit/c6069b6c35935312f068c1c00a64ae7fe0674f06

I caught the mistake quickly, I just forgot to push that update to master right away.
