### ISSUE TITLE
Internal Server Error after last release

### ISSUE THREAD

**Issue by mattenz** [nosmokingbandit/watcher#205]
I updated to the latest release 76391d6 from bd4e571 and initially everything seemed ok but now I can't load Watcher at all and receive an Internal Server Error with the following:
```
ERROR 2017-02-04 18:39:51,482 cherrypy.error.27506784.error: [04/Feb/2017:18:39:51] HTTP 
Traceback (most recent call last):
  File "c:\watcher\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "c:\watcher\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "c:\watcher\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "c:\watcher\templates\status.py", line 48, in default
    self.movie_list()
  File "c:\watcher\templates\status.py", line 105, in movie_list
    span(data['rated'], cls='rated')
  File "c:\watcher\templates\dominate\tags.py", line 63, in __init__
    super(html_tag, self).__init__(*args, **kwargs)
  File "c:\watcher\templates\dominate\dom_tag.py", line 93, in __init__
    self.add(*args)
  File "c:\watcher\templates\dominate\dom_tag.py", line 204, in add
    raise ValueError('%r not a tag or string.' % obj)
ValueError: None not a tag or string.
```
Running on Windows Server 2016 with Python 2.7.

**Comment by WilliamJBrown** [comment]
Also getting this and 500 internal server error. 

`Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/templates/settings.py", line 36, in page_template
    page(self, config)
  File "/opt/watcher/app/templates/settings.py", line 186, in search
    i(id='imdbsync', cls='fa fa-square-o checkbox', value=str(c[c_s]['Watchlists']['imdbsync']))
KeyError: 'Watchlists'`

**Comment by breyentin** [comment]
I have the error today as well

Traceback (most recent call last):
  File "D:\Watcher\watcher-master\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "D:\Watcher\watcher-master\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "D:\Watcher\watcher-master\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "D:\Watcher\watcher-master\templates\status.py", line 48, in default
    self.movie_list()
  File "D:\Watcher\watcher-master\templates\status.py", line 105, in movie_list
    span(data['rated'], cls='rated')
  File "D:\Watcher\watcher-master\templates\dominate\tags.py", line 63, in __init__
    super(html_tag, self).__init__(*args, **kwargs)
  File "D:\Watcher\watcher-master\templates\dominate\dom_tag.py", line 93, in __init__
    self.add(*args)
  File "D:\Watcher\watcher-master\templates\dominate\dom_tag.py", line 204, in add
    raise ValueError('%r not a tag or string.' % obj)
ValueError: None not a tag or string.

**Comment by mattenz** [comment]
Todays update hasn't resolved the issue.

**Comment by nosmokingbandit** [comment]
@mattenz 

Send me your watcher.sqlite file.

watchernzb@gmail.com

This is not the result of an update. A movie you added has information that is causing a problem.

**Comment by WilliamJBrown** [comment]
Can confirm this is for all movies. It says Could not find imdb id for movie name.
Try entering imdb id in search bar.

When you put in the IMDB id in the search bar and quick add it. When you then go to the status page it throws the error. Am emailing information now.

**Comment by Elfman72** [comment]
I think I was getting this with my imdb watchlist import.  Fresh install is fine.  Upon first watchlist sync, I would then get this error.  So there is something about certain movies on IMDB that Watcher doesn't seem to like ( or the SQLite db).

**Comment by ptcfast2** [comment]
I have the same issue. Have not added any new movies recently. Watcher was set to auto update.

**Comment by nosmokingbandit** [comment]
OMDB has been having some trouble this week. Someone is abusing their api by making 300+ MILLION requests in a single hour. They typically get under 50M an hour. Until they get their situation figured out things will be a little spotty. There is no way around this because TMDB doesn't supply IMDB ids and those are necessary for indexer searches.

This is the reason for the problems opening /status. Since OMDB was down, some fields in the database could not be filled and when they weren't found the template engine threw an error.

Commit 5413a7f666558288e9ffc5c0e5591c29e0fc3d0a bypasses this (there is no *critical* information missing, just the MPAA rating).

Everything is still running normally, you just can't open the /status page until you update. The automatic updater is still running, or you can just go to /settings/server and manually update.

**Comment by mattenz** [comment]
The 5413a7f commit has fixed the issue for me, thanks!

**Comment by nosmokingbandit** [comment]
It doesn't fix the problem, just the symptoms of the problem. Which is really all I can do.

**Comment by ridizy** [comment]
After adding a movie yesterday, I'm experiencing this same issue on the /status page.  I'm on f4f9db8066ae3df7319bfdc50e27412fbf9b27a1
