### ISSUE TITLE
Post-processing TypeError

### ISSUE THREAD

**Issue by Technifocal** [nosmokingbandit/watcher#206]
#### What happened?
NZBGet called the postprocessing script, which failed. Watcher logged:

```
INFO 2017-02-05 13:27:16,612 core.postprocessing.POST: #################################
INFO 2017-02-05 13:27:16,612 core.postprocessing.POST: Post-processing request received.
INFO 2017-02-05 13:27:16,612 core.postprocessing.POST: #################################
INFO 2017-02-05 13:27:16,612 core.postprocessing.get_filename: Finding movie file.
INFO 2017-02-05 13:27:16,613 core.postprocessing.get_filename: Post-processing file /downloads/completed/Movies/${PATH}/${FILE}.iso.
INFO 2017-02-05 13:27:16,613 core.postprocessing.POST: Parsing release name for information.
ERROR 2017-02-05 13:27:16,613 cherrypy.error.140267935882832.error: [05/Feb/2017:13:27:16] HTTP
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/core/postprocessing.py", line 75, in POST
    data.update(self.parse_filename(data['filename']))
  File "/opt/watcher/app/core/postprocessing.py", line 262, in parse_filename
    filepath = data['filepath']

```

#### What was supposed to happen?

Postprocessing successed.

#### How can I reproduce this?

Brand new installation, up-to-date, run:

$ `curl -X POST --data 'guid=${STRIPPED}&path=%2Fdownloads%2Fcompleted%2FMovies%2F${PATH}.Watcher&apikey=${API-KEY}&downloadid=${NUMBER}&mode=complete' http://watcher:9090/postprocessing/`

You'll get this response:

```
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>500 Internal Server Error</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>500 Internal Server Error</h2>
        <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/core/postprocessing.py", line 75, in POST
    data.update(self.parse_filename(data['filename']))
  File "/opt/watcher/app/core/postprocessing.py", line 261, in parse_filename
    filepath = data['filepath']
TypeError: string indices must be integers
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy unknown</a>
      </span>
    </div>
    </body>
</html>
```

And the log in "What happened" gets dumped to Watcher's log file.

**Comment by MartinAyla** [comment]
I have that exact error with my nzbget postprocessing script, was just about to post an error log.

**Comment by nosmokingbandit** [comment]
Fixed in commit 555b4b10535a5f28d4ca4f81f65e4dece29fa332

**Comment by nosmokingbandit** [comment]
819f9e2677ebdac6c899922169c06d46a3745aec should do it.

**Comment by Technifocal** [comment]
@nosmokingbandit Can confirm that works, although something else now doesn't. Give me a few minutes to test and I'll make an issue/pull request.

**Comment by nosmokingbandit** [comment]
There was some type errors coming up, but I fixed those a few minutes ago.
