### ISSUE TITLE
postprocess script crasht when there are no leftovers

### ISSUE THREAD

**Issue by SuperPotatoMen** [nosmokingbandit/watcher#216]
#### What happened?
The postprocess script crasht when there are no leftovers after a failed download.
#### What was supposed to happen?
picking the next release but that doesn't happend.
#### How can I reproduce this?

I use the Completion-Propagation/DMCA/Retention check script in nzbget.
(http://forum.nzbget.net/viewtopic.php?f=8&t=1736)
That script checks in 6 seconds if the download will fail or doesn't fail (mutch faster then waiting that nzbget say it doesn't work) if it fail it will block the download and force to fail in nzbget and marked the nzb "bad" No files are download then. Its look like the postproces script watcher can't handle the situation when there are no files to delete.

```
INFO 2017-02-12 15:23:51,414 core.postprocessing.POST: Post-processing as Failed.
INFO 2017-02-12 15:23:51,414 core.postprocessing.failed: Marking guid as Bad.
INFO 2017-02-12 15:23:51,414 core.updatestatus.searchresults: Marking guid https://nzbplanet.net/getnzb/a9eeb02525edfe91fdf3632757da590d.nzb&i=94621&r=6d824d8d3f12ba4b8df1f274c68827e0 as Bad.
INFO 2017-02-12 15:23:51,417 core.updatestatus.searchresults: Marking https://nzbplanet.net/getnzb/a9eeb02525edfe91fdf3632757da590d.nzb&i=94621&r=6d824d8d3f12ba4b8df1f274c68827e0 as Bad in SEARCHRESULTS.
INFO 2017-02-12 15:23:51,417 core.sqldb.update: Updating https://nzbplanet.net/getnzb/a9eeb02525edfe91fdf3632757da590d.nzb&i=94621&r=6d824d8d3f12ba4b8df1f274c68827e0 to Bad in SEARCHRESULTS.
INFO 2017-02-12 15:23:51,427 core.updatestatus.searchresults: Successfully marked https://nzbplanet.net/getnzb/a9eeb02525edfe91fdf3632757da590d.nzb&i=94621&r=6d824d8d3f12ba4b8df1f274c68827e0 as Bad in SEARCHRESULTS.
INFO 2017-02-12 15:23:51,428 core.updatestatus.markedresults: Marking https://nzbplanet.net/getnzb/a9eeb02525edfe91fdf3632757da590d.nzb&i=94621&r=6d824d8d3f12ba4b8df1f274c68827e0 as Bad in MARKEDRESULTS.
INFO 2017-02-12 15:23:51,428 core.sqldb.update: Updating https://nzbplanet.net/getnzb/a9eeb02525edfe91fdf3632757da590d.nzb&i=94621&r=6d824d8d3f12ba4b8df1f274c68827e0 to Bad in MARKEDRESULTS.
INFO 2017-02-12 15:23:51,438 core.updatestatus.markedresults: Successfully marked https://nzbplanet.net/getnzb/a9eeb02525edfe91fdf3632757da590d.nzb&i=94621&r=6d824d8d3f12ba4b8df1f274c68827e0 as Bad in MARKEDRESULTS.
INFO 2017-02-12 15:23:51,440 core.postprocessing.failed: Setting MOVIE status.
INFO 2017-02-12 15:23:51,440 core.sqldb.get_distinct: Getting distinct values for tt2404435 in SEARCHRESULTS
INFO 2017-02-12 15:23:51,440 core.updatestatus.movie_status: Setting MOVIES tt2404435 status to Found.
INFO 2017-02-12 15:23:51,440 core.sqldb.update: Updating tt2404435 to Found in MOVIES.
INFO 2017-02-12 15:23:51,451 core.postprocessing.failed: Deleting leftover files from failed download.
ERROR 2017-02-12 15:23:51,451 cherrypy.error.75424048.error: [12/Feb/2017:15:23:51] HTTP 
Traceback (most recent call last):
  File "C:\watcher\watcher-master\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\watcher\watcher-master\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\watcher\watcher-master\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\watcher\watcher-master\core\postprocessing.py", line 94, in POST
    response = self.failed(data)
  File "C:\watcher\watcher-master\core\postprocessing.py", line 456, in failed
    if data['imdbid'] and data['quality']:
KeyError: 'quality'
INFO 2017-02-12 15:23:51,471 cherrypy.error.75424048.error: [12/Feb/2017:15:23:51] HTTP 
Request Headers:
  HOST: localhost:9090
  CONNECTION: close
  Remote-Addr: 127.0.0.1
  Content-Length: 315
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  ACCEPT-ENCODING: identity
```

**Comment by nosmokingbandit** [comment]
For some reason I removed the Quality key when processing a failed download, which it kind of needs. Or this happens.

This has been fixed, but I've been having git problems so I don't know exactly what commit did it. But one of them did.

**Comment by SuperPotatoMen** [comment]
Cool. i will test the fix now. give me a moment :)

**Comment by SuperPotatoMen** [comment]
@nosmokingbandit thanks fixs worked!

`INFO 2017-02-12 23:11:19,967 core.updatestatus.movie_status: Setting MOVIES tt2404435 status to Found.
INFO 2017-02-12 23:11:19,967 core.sqldb.update: Updating tt2404435 to Found in MOVIES.
INFO 2017-02-12 23:11:19,967 core.postprocessing.failed: Deleting leftover files from failed download.
INFO 2017-02-12 23:11:19,967 core.snatcher.auto_grab: Selecting best result for tt2404435
INFO 2017-02-12 23:11:19,967 core.sqldb.get_search_results: Retreving Search Results for tt2404435.
INFO 2017-02-12 23:11:19,983 core.snatcher.snatch_nzb: Sending nzb to NzbGet.`
