### ISSUE TITLE
Importing existing library

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/watcher#222]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?

Cannot import library and throws a error in the logs. Not sure whats happening. 

#### What was supposed to happen?

Import the existing library. 

#### How can I reproduce this?

```
INFO 2017-02-17 19:55:37,124 core.library.scan_dir: Scanning /volume2/Storage/Movies/ for movies.
INFO 2017-02-17 19:55:37,147 cherrypy.error.139946384808400.error: [17/Feb/2017:19:55:37] HTTP 
Request Headers:
  Content-Length: 69
  COOKIE: list_style=compact; rememberMe="\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNDg3MzA3MDY3LCJtYXlTZWVBZG1pbiI6dHJ1ZSwiZXhwIjoxNDg4NTE2NjY3LCJtYXlTZWVTdGF0cyI6dHJ1ZX0.yj3_bOa_7GIeePy6CnixWICJ-n_es2sr5KPEmHmyYJ8\""; stay_login=0; session=21a86487-c41c-40a8-ab37-c62ca40c05a0; session_id=93153abad1b4d8e3a7fe5a99cf34d462973ae700
  HOST: 192.168.1.190:9090
  ORIGIN: http://192.168.1.190:9090
  CONNECTION: keep-alive
  Remote-Addr: 172.17.42.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-CA,en-GB;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  REFERER: http://192.168.1.190:9090/import_library
  ACCEPT-ENCODING: gzip, deflate
ERROR 2017-02-17 19:55:37,147 cherrypy.error.139946384808400.error: [17/Feb/2017:19:55:37] HTTP 
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/core/ajax.py", line 644, in scan_library
    movies = self.library.scan_dir(directory, minsize, recursive)
  File "/opt/watcher/app/core/library.py", line 34, in scan_dir
    for root, dirs, filenames in os.walk(directory):
  File "/usr/lib64/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/posixpath.py", line 71, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 5: ordinal not in range(128)
```

**Comment by nosmokingbandit** [comment]
Apparently os.walk can act stupid when unicode characters are involved. I couldn't replicate this, but update to 53cf165f182502d60fabd04bf78bee0b33f79d3a and give it another shot.

**Comment by WilliamJBrown** [comment]
Still looks to be the same thing. Is there anything I can do to get more information for you? 

```
INFO 2017-02-17 21:50:15,937 core.library.scan_dir: Scanning /volume2/Storage/Movies/ for movies.
INFO 2017-02-17 21:50:15,964 cherrypy.error.139941602179280.error: [17/Feb/2017:21:50:15] HTTP 
Request Headers:
  COOKIE: session_id=f7026b68a596b2bf28317083ae2046f1d54007e4
  ORIGIN: https://watcher.wjbrown.host
  Remote-Addr: 172.17.42.1
  X-REAL-IP: 192.168.1.1
  Content-Length: 69
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
  CONNECTION: close
  REFERER: https://watcher.wjbrown.host/import_library
  X-REQUESTED-WITH: XMLHttpRequest
  X-FORWARDED-PROTO: https
  HOST: watcher.wjbrown.host
  ACCEPT: */*
  ACCEPT-LANGUAGE: en-CA,en-GB;q=0.8,en-US;q=0.6,en;q=0.4
  X-FORWARDED-FOR: 192.168.1.1
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  ACCEPT-ENCODING: gzip, deflate, br
ERROR 2017-02-17 21:50:15,964 cherrypy.error.139941602179280.error: [17/Feb/2017:21:50:15] HTTP 
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/core/ajax.py", line 644, in scan_library
    movies = self.library.scan_dir(directory, minsize, recursive)
  File "/opt/watcher/app/core/library.py", line 34, in scan_dir
    for root, dirs, filenames in os.walk(directory):
  File "/usr/lib64/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/posixpath.py", line 71, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 5: ordinal not in range(128)
```

**Comment by nosmokingbandit** [comment]
The traceback isn't super helpful, but I'm pretty sure it is some kind of unicode character making os.walk choke, but I've tried it with a unicode file and directory and it worked for me.

Do you have any weird folder or file names?

**Comment by WilliamJBrown** [comment]
It is mounted in the same place for my post processing end point. 

I use a folder format of Video/Movies/Movie Name (year)/Movies Name (year).mkv

Maybe the brackets?

**Comment by nosmokingbandit** [comment]
I was able to make it crash using russian characters, so at least I have something to work with now. I still haven't a clue how to fix it, but I'm looking at it.

**Comment by nosmokingbandit** [comment]
I'm still not able to get this to consistently fail for me, but commit 3007c9e3e1046d89da9ba8bc34740a99a5e74b73 *might* take care of it.

It seems to be stemming from os.path.join() being called in os.walk, so I just wrote my own directory scanner instead and hopefully it works better.

**Comment by WilliamJBrown** [comment]
hmm sorry but still the same error is being thrown.

```
INFO 2017-02-18 01:45:53,972 core.library.scan_dir: Scanning /volume2/Storage/Movies/ for movies.
INFO 2017-02-18 01:45:54,033 cherrypy.error.139636286912784.error: [18/Feb/2017:01:45:54] HTTP 
Request Headers:
  Content-Length: 69
  COOKIE: list_style=compact; rememberMe="\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNDg3MzA3MDY3LCJtYXlTZWVBZG1pbiI6dHJ1ZSwiZXhwIjoxNDg4NTE2NjY3LCJtYXlTZWVTdGF0cyI6dHJ1ZX0.yj3_bOa_7GIeePy6CnixWICJ-n_es2sr5KPEmHmyYJ8\""; session=21a86487-c41c-40a8-ab37-c62ca40c05a0; stay_login=0; session_id=2b9a3a6d7f42a4f87419c4fa51fb7fe16d5cef1b
  HOST: 192.168.1.190:9090
  ORIGIN: http://192.168.1.190:9090
  CONNECTION: keep-alive
  Remote-Addr: 172.17.42.1
  ACCEPT: */*
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
  X-REQUESTED-WITH: XMLHttpRequest
  ACCEPT-LANGUAGE: en-CA,en-GB;q=0.8,en-US;q=0.6,en;q=0.4
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  REFERER: http://192.168.1.190:9090/import_library
  ACCEPT-ENCODING: gzip, deflate
ERROR 2017-02-18 01:45:54,034 cherrypy.error.139636286912784.error: [18/Feb/2017:01:45:54] HTTP 
Traceback (most recent call last):
  File "/opt/watcher/app/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/watcher/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher/app/core/ajax.py", line 644, in scan_library
    movies = self.library.scan_dir(directory, minsize, recursive)
  File "/opt/watcher/app/core/library.py", line 34, in scan_dir
    files = self._walk(directory)
  File "/opt/watcher/app/core/library.py", line 201, in _walk
    full_path = os.path.join(directory, i)
  File "/usr/lib64/python2.7/posixpath.py", line 71, in join
    path +=  b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 5: ordinal not in range(128)
INFO 2017-02-18 01:46:36,967 core.version.update_check: Checking git for a new version.
INFO 2017-02-18 01:46:37,278 core.version.update_check: Current local hash: 7f544c14d8dcb033195ca8cabdc15650ae00ad44
INFO 2017-02-18 01:46:43,943 core.sqldb.get_user_movies: Retreving list of user's movies.
```

Again not sure what is happening. Would it help to change browsers or something else that can get you more info?

**Comment by nosmokingbandit** [comment]
This is actually somewhat helpful because I know the problem is specifically the os.path.join() method.

The source for os.path.join is pretty basic stuff, which doesn't indicate any reason it should choke.

In commit f2d27337ed20e2eca71614afd4a01cb797f1c23d I adding an extra logging line right before the exception should occur. I hate to have you jump through hoops like this, but update, try it again, then we can take a look at the log and see exactly what string is causing it to throw an exception.

**Comment by WilliamJBrown** [comment]
Shot an email off to you. Not a problem at all to get to the bottom of this!

Anything you need just ask.

**Comment by nosmokingbandit** [comment]
Disregard the last email I sent you. I ended up forcing utf-8 encoding on
everything anyway. Things are easier for me this way.

I don't know if will affect your library import at all, but update and give
it another shot.

**Comment by WilliamJBrown** [comment]
Getting further by the looks of it but a lot is not finding something:

```
ERROR 2017-02-21 03:06:04,276 core.movieinfo.get_imdbid: TMDB find.
Traceback (most recent call last):
  File "/opt/watcher/app/core/movieinfo.py", line 134, in get_imdbid
    response = json.load(urllib2.urlopen(request))
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 429: 
WARNING 2017-02-21 03:06:04,276 core.library.get_metadata: Unable to find imdbid.

```

**Comment by WilliamJBrown** [comment]
Sent the full log to email.

**Comment by nosmokingbandit** [comment]
This is weird because that shouldn't cause the loop to break.

I'll take a look at your logs again. Thanks.

**Comment by nosmokingbandit** [comment]
In https://github.com/nosmokingbandit/watcher/commit/60d371b01a2b180304212af18c0968c777d73088 I implemented rate limiting for TMDB, which I believe to be the problem. Importing might be slightly slower, but it has the benefit of maybe actually working now, so that will be nice.

Let me know if this makes any difference.

**Comment by jaketame** [comment]
Safari Console Error - No errors in watcher log
[Error] Failed to load resource: the server responded with a status of 504 (Gateway Time-out) (scan_library, line 0) watcher/ajax/scan_library

**Comment by nosmokingbandit** [comment]
Do you know how long that was running before the error occurred?

I'm thinking the ajax request from the browser it timing out with large imports. Jquery officially doesn't have a timeout value, so it depends on the browser. *If* that is the problem, of course.

I have half a mind to try switching the interface to websockets, but that is a lot of work.

**Comment by nosmokingbandit** [comment]
Double posting is evil but I want you all to be alerted of this.

Today I changed a lot of the import/scanning process. I'm 90% sure the problem is browsers abandoning a long-running ajax request. Update to at least https://github.com/nosmokingbandit/watcher/commit/e30cbec25e0a2a2c9d2636b5c6525fc66236958f and see if the metadata gathering actually finishes.

Just before that commit I changed how rate limiting on TMDB's api works, so that should help avoid a lot of missing information as well.

**Comment by jaketame** [comment]
Sorry for late reply. I will give it a whirl and report back. Yes it looked like AJAX was timing out.

Will the commit you mention still query each file for metadata?

**Comment by nosmokingbandit** [comment]
It has to check each file so it knows what it is.

This repo will no longer be updated, check out https://github.com/nosmokingbandit/watcher3.

While porting to python3 I changed a lot of the import functions to make things a bit more streamlined. It will still need to read the header of each file to know what it is, but the new ajax handling isn't really capable of timing out.
