### ISSUE TITLE
post processing script fails for NZBGET

### ISSUE THREAD

**Issue by mpalpha** [nosmokingbandit/watcher#230]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
the nzbget.py post processing script fails with an unknown error when executed by nzbget

ERROR	Post-process-script watcher.py for *********filename******** failed (terminated with unknown status)
INFO	watcher: urllib2.HTTPError: HTTP Error 500: Internal Server Error
INFO	watcher: raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
INFO	watcher: File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
INFO	watcher: result = func(*args)
INFO	watcher: File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
INFO	watcher: return self._call_chain(*args)
INFO	watcher: File "/usr/lib/python2.7/urllib2.py", line 473, in error
INFO	watcher: 'http', request, response, code, msg, hdrs)
INFO	watcher: File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
INFO	watcher: response = meth(req, response)
INFO	watcher: File "/usr/lib/python2.7/urllib2.py", line 435, in open
INFO	watcher: return opener.open(url, data, timeout)
INFO	watcher: File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
INFO	watcher: response = json.loads(urllib2.urlopen(request, timeout=600).read())
INFO	watcher: File "/scripts/watcher.py", line 61, in <module>
INFO	watcher: Traceback (most recent call last):
INFO	watcher: Sending *********filename******** to Watcher as Complete.
INFO	Executing post-process-script watcher.py for *********filename********

#### What was supposed to happen?
the script should return success, it worked just fine about a week ago.

#### How can I reproduce this?
install the nzbget.py into nzbget and configure the api key etc, then trigger a download

Including logs of the event are often neccessary to find out exactly what is going on.
If the log section is short feel free to post is here, but make sure to remove any personal information (ie IP address) and remove any references to movie or release titles.
If the logs are long, or require release title names to troubleshoot, submit an issue here, then send the logs to watchernzb@gmail.com.
Put a link to your issue in the email body so we know exactly who it belongs to.

**Comment by nosmokingbandit** [comment]
I'll need the Watcher logs from this post-processing request.

**Comment by mpalpha** [comment]
it doesn't reach watcher, its the nzbget.py script.

**Comment by nosmokingbandit** [comment]
It does reach Watcher. That is where the 500 response is coming from.

**Comment by mpalpha** [comment]
Doh, I'll try to find it.

**Comment by mpalpha** [comment]
this is the only http error I get in my watcher logs

INFO 2017-03-07 22:24:56,739 core.library.get_metadata: Gathering
metada for /movies/Road House (1989)/road.house.mkv.
ERROR 2017-03-07 22:24:56,990 core.movieinfo.get_imdbid: Error
attempting to get TMDBID from TMDB.
Traceback (most recent call last):
  File "/watcher/core/movieinfo.py", line 169, in get_imdbid
    response = json.load(urllib2.urlopen(request))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 429:
WARNING 2017-03-07 22:24:56,992 core.library.get_metadata: Unable to
find imdbid.

**Comment by nosmokingbandit** [comment]
What version of Watcher are you running?

In commit https://github.com/nosmokingbandit/watcher/commit/516e2c423b2e63cfd8f3cd26552ba52d801147fb I limited the rate of calls to TheMovieDatabase's api even more to help avoid these errors.

The HTTP Error 429 near the end of the log means your ip address is making too many requests to their api. This could be from something else on your network sending tmdb queries as well. With the latest rate limiting I fired off requests as fast as possible for 5 minutes and everything was ok, so this is unexpected.

I'll probably limit the request rate even more just in case you have Kodi or something sending out requests as well. Every IP address gets 40 api hits every ten seconds, so I limit Watcher to 35 hits that regenerate at 3.5/second. The only time I need to send a lot of requests quickly is when a user imports a library, and the rate I got of ~1.25/second is plenty fast enough.

Of course this only helps if other apps on your network over-limit requests as well.
