### ISSUE TITLE
Import files - MemoryError

### ISSUE THREAD

**Issue by CryoSkyd** [nosmokingbandit/watcher#240]
Having a problem? Bummer. Watcher is under constant development, so bear with us while we sort this out.

Meanwhile, you can help us get this fixed more quickly by following this format:

#### What happened?
Importing a large collection of files will cause the process to stop mid way through. Looking at log files, it seems to be caused by a MemoryError from the cherrypy module.

#### How can I reproduce this?
Import a large folder

#### What else do I need to know?
Windows 10, Python 2.7.11, 8GB Ram, Only 5GB in use during error

Log file:
```
INFO 2017-03-19 05:06:10,894 core.library.get_metadata: Gathering metada for FILE_A
ERROR 2017-03-19 05:09:30,878 core.library.get_metadata: Unable to parse metadata from file header.
Traceback (most recent call last):
  File "C:\Git\Watcher\watcher\core\library.py", line 90, in get_metadata
    filedata = extractor.exportDictionary(human=False)
AttributeError: 'NoneType' object has no attribute 'exportDictionary'
ERROR 2017-03-19 05:09:30,977 core.movieinfo.get_imdbid: Error attempting to get TMDBID from TMDB.
Traceback (most recent call last):
  File "C:\Git\Watcher\watcher\core\movieinfo.py", line 177, in get_imdbid
    response = json.load(urllib2.urlopen(request))
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 431, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 449, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1240, in https_open
    context=self._context)
  File "C:\Python27\lib\urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error malloc failure (_ssl.c:590)>
WARNING 2017-03-19 05:09:30,993 core.library.get_metadata: Unable to find imdbid.
INFO 2017-03-19 05:09:30,993 core.ajax.scan_library: IMDB unknown for import TITLE_A
INFO 2017-03-19 05:09:30,993 core.library.get_metadata: Gathering metada for FILE_B.
ERROR 2017-03-19 05:09:31,595 cherrypy.error.62500624.error: [19/Mar/2017:05:09:31]  Traceback (most recent call last):
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 189, in trap
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 286, in __next__
    return next(self.iter_response)
  File "C:\Git\Watcher\watcher\lib\cherrypy\lib\encoding.py", line 100, in encoder
    for chunk in body:
  File "C:\Git\Watcher\watcher\core\ajax.py", line 675, in scan_library
MemoryError

ERROR 2017-03-19 05:09:31,609 cherrypy.error.62500624.error: [19/Mar/2017:05:09:31]
Traceback (most recent call last):
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 215, in trap
    self.start_response(s, h, _sys.exc_info())
  File "C:\Git\Watcher\watcher\lib\cherrypy\wsgiserver\__init__.py", line 2357, in start_response
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 286, in __next__
    return next(self.iter_response)
  File "C:\Git\Watcher\watcher\lib\cherrypy\lib\encoding.py", line 100, in encoder
    for chunk in body:
  File "C:\Git\Watcher\watcher\core\ajax.py", line 675, in scan_library
MemoryError
ERROR 2017-03-19 05:09:31,678 cherrypy.error.error: [19/Mar/2017:05:09:31] ENGINE MemoryError()
Traceback (most recent call last):
  File "C:\Git\Watcher\watcher\lib\cherrypy\wsgiserver\__init__.py", line 1406, in communicate
  File "C:\Git\Watcher\watcher\lib\cherrypy\wsgiserver\__init__.py", line 860, in respond
  File "C:\Git\Watcher\watcher\lib\cherrypy\wsgiserver\__init__.py", line 2333, in respond
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 177, in __next__
    return self.trap(next, self.iter_response)
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 215, in trap
    self.start_response(s, h, _sys.exc_info())
  File "C:\Git\Watcher\watcher\lib\cherrypy\wsgiserver\__init__.py", line 2357, in start_response
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 189, in trap
    return func(*args, **kwargs)
  File "C:\Git\Watcher\watcher\lib\cherrypy\_cpwsgi.py", line 286, in __next__
    return next(self.iter_response)
  File "C:\Git\Watcher\watcher\lib\cherrypy\lib\encoding.py", line 100, in encoder
    for chunk in body:
  File "C:\Git\Watcher\watcher\core\ajax.py", line 675, in scan_library
MemoryError
```

**Comment by haoyuchen** [comment]
I was able to get a successful import by installing python 64bit to avoid the memory error.  However, I think maybe there's some way to chunk the import process so it doesn't hit memory issues even on 32bit?

**Comment by nosmokingbandit** [comment]
This is really weird. The module throwing the memory alloc error is urllib2, which is just used to get info from TMDB, which is very small.

After some quick googling it looks like urllib2 has a memory leak problem on Windows.

After more googling it looks like this is a known issue since 2009 and python hasn't patched it. Something about the DNS looking causing a memory leak. I'm sure someone already has a patch for it, I just need to find what works best.

**Comment by nosmokingbandit** [comment]
I'm going to go ahead and close this. I just ran a quick test import of 99 movies and my ram usage peaked at 37mb. It was at 34.5 until the database writing started, so I might look at that to see if I can make it more efficient, but gathering metadata seemed very smooth.

I just realized the absurdity of trying to optimize less than 3mb of ram usage. I'm still going to do it though.

**Comment by CryoSkyd** [comment]
Cool, thanks for looking into it. I'll test with your new commit and see if closing the file handlers addresses the issue. 
For reference, I was importing ~850 movies and it usually broke somewhere in the 400-600s.
