### ISSUE TITLE
Torznab not finding anything with French trackers (Jackett)

### ISSUE THREAD

**Issue by OldMike** [nosmokingbandit/watcher#248]
Hi

#### What happened?
Can't find any movie using Jackett with French trackers. It's ok with NZBgeek etc.
"Nothing found yet."

#### How can I reproduce this?
Here's an example for Rogue One but it can't find anything.

#### What else do I need to know?
OS: Linux Control 4.4.44-1-pve #1 SMP PVE 4.4.44-84 (Thu, 9 Mar 2017 12:06:34 +0100) x86_64 GNU/Linux
Python: Python 2.7.9
Watcher build: Current version hash: de13996

Logs
```
INFO 2017-03-26 07:26:41,276 core.sqldb.get_user_movies: Retreving list of user's movies.
INFO 2017-03-26 07:26:41,054 core.sqldb.get_search_results: Retreving Search Results for tt3748528.
INFO 2017-03-26 07:26:40,801 core.searcher.search: 0 results found.
INFO 2017-03-26 07:26:40,801 core.sqldb.get_search_results: Retreving Search Results for tt3748528.
INFO 2017-03-26 07:26:40,191 root.search_newznab: SEARCHING: http://xxx:xx/torznab/hdonly/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
HTTPError: HTTP Error 500: Internal Server Error
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    r = urllib2.urlopen(request, timeout=timeout)
  File "/home/mike/watcher-master/core/helpers.py", line 58, in open
    response = Url.open(request)
  File "/home/mike/watcher-master/core/providers/base.py", line 50, in search_newznab
Traceback (most recent call last):
ERROR 2017-03-26 07:26:40,191 root.search_newznab: Newz/TorzNab backlog search.
INFO 2017-03-26 07:26:39,389 root.search_newznab: SEARCHING: http://xxx:xx/torznab/elitetracker/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
INFO 2017-03-26 07:26:38,282 root.search_newznab: SEARCHING: http://xxx:xx/torznab/xthor/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
INFO 2017-03-26 07:26:37,511 root.search_newznab: SEARCHING: http://xxx:xx/torznab/qctorrent/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
timeout: timed out
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 444, in begin
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 1111, in getresponse
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/urllib2.py", line 1200, in do_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1227, in http_open
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    r = urllib2.urlopen(request, timeout=timeout)
  File "/home/mike/watcher-master/core/helpers.py", line 58, in open
    response = Url.open(request)
  File "/home/mike/watcher-master/core/providers/base.py", line 50, in search_newznab
Traceback (most recent call last):
ERROR 2017-03-26 07:26:37,511 root.search_newznab: Newz/TorzNab backlog search.
INFO 2017-03-26 07:26:07,487 root.search_newznab: SEARCHING: http://xxx:xx/torznab/t411/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
INFO 2017-03-26 07:26:05,884 core.sqldb.get_search_results: Retreving Search Results for tt3748528.
INFO 2017-03-26 07:26:05,883 core.sqldb.get_movie_details: Retreving details for tt3748528
```

**Comment by nosmokingbandit** [comment]
There are two errors in the log.

First: HTTPError: HTTP Error 500: Internal Server Error

This means either Jackett or the indexer had a problem. The Jackett logs might tell you what the actual problem is. Sometimes this happens once and never happens again. Is it consistently a 500 response for hdonly?

Second: timeout: timed out

This one's obvious, but the reason *why* it timed out isn't clear. It this consistent with qctorrent?

Try entering the urls in your browser:
http://xxx:xx/torznab/hdonly/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000
and
http://xxx:xx/torznab/qctorrent/api?apikey=APIKEY&q=tt3748528&t=search&cat=2000

One of three things will happen.
1) You get an error similar to your Watcher logs. If this is the case something isn't working correctly with Jackett or your indexer.

2) You get an empty list of results that looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<rss version="1.0" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:torznab="http://torznab.com/schemas/2015/feed">
  <channel>
    <atom:link href="http://127.0.0.1:9117/" rel="self" type="application/rss+xml" />
    <title>The Pirate Bay</title>
    <description />
    <link>https://thepiratebay.org/</link>
    <lanuage>en-us</lanuage>
    <category>search</category>
    <image>
      <url>http://127.0.0.1:9117/logos/thepiratebay.png</url>
      <title>The Pirate Bay</title>
      <link>https://thepiratebay.org/</link>
      <description>The Pirate Bay</description>
    </image>
  </channel>
</rss>
```

If this happens your indexer doesn't support imdbid search. I'm working on a fix for this.

3) You get a bunch of search results. If this happens I need to dig a little deeper, but lets not worry about that until the easy solutions are tested.

Let me know what you come up with and I'll see what I can do.

**Comment by OldMike** [comment]
Hi,

I updated Watcher this morning.
Jackett is quite* okay, I already use it with Medusa, Sickrage, Radarr and Couchpotato.
* 1 problem with T411, guess due to the domain transfer.
Jackett and Watcher (and CP, Radarr etc) are on the same CT.


Interesting thing is Jackett found some files
`Found 32 releases from Xthor for: tt3748528`
But the strange one is it doesn't find any rlz on other trackers like HD-Only, but i can manually find some for this movie
`Found 0 releases from HD-Only for: tt3748528`
Moreover, looking at the Watchers logs, I can see many
`INFO 2017-03-27 06:34:24,759 core.scoreresults.fuzzy_title: Keeping 0 results.
DEBUG 2017-03-27 06:34:24,758 core.scoreresults.fuzzy_title: money+monster+2016+multi+truefrench+1080p+bluray+x264+melba best title match was 33%, removing search result.` I checked all the lines, not one is mentioning the searched movie so I don't understand the meaning of this.

**Comment by nosmokingbandit** [comment]
I won't be updating this repo any longer, but I believe this is solved in https://github.com/nosmokingbandit/watcher3. 

HD-Only doesn't support imdbid searches, so that explains the lack of results there. When porting to Python3, I made Watcher check all torznab indexer's capabilities when searching.

Try that out and file an issue at https://github.com/nosmokingbandit/watcher3 if you are still having trouble.
