### ISSUE TITLE
sabnzbd.py Errors

### ISSUE THREAD

**Issue by Scoboose** [nosmokingbandit/watcher#41]
First thing I ran into was
 `
           Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\Scripts\sabnzbd.py", line 32, in <module>
    watcherapi = conf['watcherkey']
KeyError: 'watcherkey'
`

So I added    `'watcherkey': 'My Watcher API key here',` to the conf at the top, and it seems to have fixed this error.

Now I am getting this
`
           Seinding My.Movie.Title.Here.Watcher to Watcher as Complete.
Traceback (most recent call last):
  File "C:\Program Files (x86)\SABnzbd\Scripts\sabnzbd.py", line 73, in <module>
    response = json.loads(urllib2.urlopen(request).read())
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Python27\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Python27\lib\urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 11001] getaddrinfo failed>`

When I correctly enter `'http://{}:{}/sabnzbd/api?apikey={}&mode=history&output=json&search={}'.format(sabhost, sabport, sabkey, name)` into my browser I get all the info displayed in my browser just fine.

Is there any way to fix this?

**Comment by Scoboose** [comment]
Using commit 16b2ffd3a38be22a1808733d5e92c3c6f93a3b4b and changeing  `'watcherapi': 'WATCHERAPIKEY',` to `'watcherkey': 'WATCHERAPIKEY',` fixed my issue!

**Comment by nosmokingbandit** [comment]
Cool beans. Sorry for the late response, this has become rather popular in a short amount of time.

I'm still getting over a pretty bad sinus infection, and I learned to be extra careful when taking lots of cough syrup and sudafed.

Sorry about the mess, but I'm glad it is working well now.
