### ISSUE TITLE
Post Process / Renamer - 500 error

### ISSUE THREAD

**Issue by kylerw** [nosmokingbandit/watcher#72]
Traceback (most recent call last):
  File "/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/watcher/core/postprocessing.py", line 102, in GET
    response = json.dumps(self.complete(data), indent=2, sort_keys=True)
  File "/watcher/core/postprocessing.py", line 444, in complete
    response = self.renamer(data)
  File "/watcher/core/postprocessing.py", line 511, in renamer
    new_name = renamer_string.format(**data).replace('  ', ' ')
KeyError: u'videocode'

**Comment by kylerw** [comment]
User error - typo with one of the renaming parameters.
