### ISSUE TITLE
DB error when searching

### ISSUE THREAD

**Issue by calebcall** [nosmokingbandit/watcher#81]
So far love this.  Even with the issues, it's already replaced CP for me (I've been using CP ever since CP was a thing, before CP server, etc).

On to the issues.  First issue is it seems the post processing is only partially working.  If the download completes successfully, then everything is good.  Watcher is notified, etc.  However, if it fails to complete, it seems watcher is never notified.  It stays in a "Snatched" state and I see nothing in the logs on non-successful downloads.  I'm using nzbget for movies.  This may be a setting in either Watcher or nzbget I'm missing.  It seems odd it's only the failures that don't work.

Second issue, auto-searching doesn't work.  I have it set to search once an hour, I see the time change of when it'll search next, but it never finds anything.  If I go in a manually search, it finds plenty of possible releases.  

Third issue, this may be (probably is) related to the second issue.  In my logs, each time auto-search runs, I get the an error in my logs that it's can't open the database file:

```
ERROR 2016-12-31 23:45:10,953 core.sqldb.execute: SQL Databse Query: SELECT * FROM MOVIES ORDER BY title ASC
Traceback (most recent call last):
  File "/Users/me/Documents/git/watcher/core/sqldb.py", line 90, in execute
    result = self.engine.execute(command)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 2057, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 2106, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 2145, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 2141, in _wrap_pool_connect
    return fn()
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/pool.py", line 516, in checkout
    rec = pool._do_get()
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/pool.py", line 1229, in _do_get
    return self._create_connection()
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
OperationalError: (sqlite3.OperationalError) unable to open database file
```

I've done a little digging and the recommendations have all been around permissions.  Since my user is the user that cloned the git repo, and the process is running as my user, it should have all the permissions it needs.  However, just to rule it out I chown'd the entire directory and everything below it to 777 and the problem persists.  I'm guessing it's trying to get a list of movies to iterate through but since it can't, it never actually auto-searches, it just updates the time of next time it will run.  Suggestions to get this working?

**Comment by calebcall** [comment]
Not sure what I did, but the first issue of post-processing only partially working seems to no longer be an issue.

**Comment by nosmokingbandit** [comment]
Does your user have r/w access to the entire Watcher folder? Sqlalchemy needs r/w to the parent folder of the database file.

**Comment by calebcall** [comment]
Yeah, as I mentioned since my user cloned this there's no reason it wouldn't have r/w to the entire directory.  However, also as mentioned, to rule that out, I chmod'd the entire watcher directory and everything below it to 777.  The problem still persisted.  

Since I had all movies in a "Completed" state except for two from running them manually, I decided to delete the sqlite db and restart the process.  That recreated the DB and I haven't seen the issue since. (That was a couple hours ago, I should have seen the error a couple times if it were still happening).

**Comment by calebcall** [comment]
Nevermind, issue still exists.  Since my starting search time was in the future (19:45) it hadn't actually auto-searched.  I just updated that to 13:00, restarted and shortly after startup it failed again with the same error.

**Comment by calebcall** [comment]
Another test, I ran the process using sudo (so it was running as root) and it still had the same permission problem.

**Comment by calebcall** [comment]
Now, instead of getting a permission denied error, I'm getting a table not found error (note, I haven't done anything with this).

```ERROR 2017-01-07 21:19:26,255 core.sqldb.execute: SQL Databse Query: SELECT * FROM MOVIES ORDER BY title ASC
Traceback (most recent call last):
  File "/Users/me/Documents/git/watcher/core/sqldb.py", line 91, in execute
    result = self.engine.execute(command)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/me/Documents/git/watcher/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: MOVIES [SQL: 'SELECT * FROM MOVIES ORDER BY title ASC']```

**Comment by soundjester** [comment]
I am also getting the same SQL error on FreeBSD, current commit `19c46392`

Error log follows:
```

INFO 2017-01-08 00:30:43,081 core.rss.predb.check_all: Checking predb.me for new available releases.
INFO 2017-01-08 00:30:43,082 core.sqldb.get_user_movies: Retreving list of user's movies.
ERROR 2017-01-08 00:30:43,084 core.sqldb.execute: SQL Databse Query: SELECT * FROM MOVIES ORDER BY title ASC
Traceback (most recent call last):
  File "/usr/share/watcher/core/sqldb.py", line 90, in execute
    result = self.engine.execute(command)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 2058, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 939, in execute
    return self._execute_text(object, multiparams, params)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1097, in _execute_text
    statement, parameters
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
    exc_info
  File "/usr/share/watcher/lib/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/share/watcher/lib/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/share/watcher/lib/sqlalchemy/engine/default.py", line 462, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: MOVIES [SQL: 'SELECT * FROM MOVIES ORDER BY title ASC']
```

**Comment by nosmokingbandit** [comment]
Get the the logs leading up to that point.

Email to watchernzb@gmail.com

**Comment by calebcall** [comment]
On mine, that is all the logs that are available for that event.  On mine, the next log is ~40mins before that event.  I'm happy to email them if you want them still.  It does spit out the Traceback twice, I assume there's some retypes logic.

I also updated the title of this to be a little more relevant.

**Comment by averagecdn** [comment]
Getting the following when attempting to search new movies.


INFO 2017-01-12 19:57:59,193 core.rss.predb.check_one: Checking predb.me for new available releases for Why Him?.
ERROR 2017-01-12 19:57:59,241 core.rss.predb.search_rss: PREDB search.
Traceback (most recent call last):
  File "/Users/mark/Downloads/watcher/core/rss/predb.py", line 79, in search_rss
    results_xml = urllib2.urlopen(request).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>
INFO 2017-01-12 19:57:59,242 core.sqldb.get_movie_details: Retreving details for tt4501244.
INFO 2017-01-12 19:57:59,262 core.sqldb.get_search_results: Retreving Search Results for tt4501244.
INFO 2017-01-12 19:57:59,270 core.sqldb.get_user_movies: Retreving list of user's movies.

**Comment by calebcall** [comment]
That's a different issue.  Are you on python 2.7.9+?  The requirements state you need to be.  There's another thread about that same issue though.
